### ISSUE TITLE
add support for splitting slotIDs and submissionLists array for the final updateRewards call

### ISSUE THREAD

**Issue by chetna-mittal** [PowerLoom/submission-sequencer-event-collector#7]
**Is your feature request related to a problem?**

The `slotIDs` and `submissionLists` array (built out from the eligible nodes set) are being send out fully.

**Describe the solution you'd like**

- Introduce splitting of `slotIDs` and `submissionLists` by using a new config param `RelayerBatchSize`
- Send out the smaller arrays to the relayer parallely (`using go routines`)
- Ensure that these are being sent out to the relayer after a certain number of epochs have crossed after the day transition

**Comment by anomit** [comment]
Will be updating the review status once the current day rolls over for our devnet markets against which these tests are running.

Related issue pending the same review in finalizer sequencer component: https://github.com/PowerLoom/submission-sequencer-finalizer/issues/6

**Comment by anomit** [comment]
Resolved by merging PR #4
